name: Legitify Analyze
on:
    workflow_dispatch:
    schedule:
      - cron: '0 11 * * 1-5'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Legitify Action
        uses: Legit-Labs/legitify@main
        with:
          github_token: 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
          ignore-policies: |
             non_admins_can_create_public_repositories
             requires_status_checks
